### ISSUE TITLE
Mandatory fields can be left blank on edit seller page.

### ISSUE THREAD

**Issue by ashika123** [ajency/Foodstree#46]
Steps:
1. Click on seller (Admin login)
2. Click edit for any of the sellers
3. Now clear the data in the mandatory fields and click on update seller

Current behaviour: Seller details can be updated by leaving the mandatory fields blank
Expected Behaviour: Mandatory fields should not be allowed to be blank on updating the seller details

**Comment by robiulpro** [comment]
Fixed

**Comment by ashika123** [comment]
This is not found to be fixed.The issue persists on the admin side.

**Comment by robiulpro** [comment]
Fixed

**Comment by ashika123** [comment]
Tested.
